# Generated by Django 5.0.7 on 2024-08-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=70)),
                ('edesg', models.CharField(max_length=70)),
                ('esal', models.IntegerField()),
            ],
        ),
    ]
